export const teamA = [
  {
    id: 1,
    name: 'Sagun',
    player_number: 1,
    jersey_color: '#FF0000',
    top: 245,
    left: 50,
    team: 'A',
  },
  {
    id: 2,
    name: 'Adarsha',
    player_number: 4,
    jersey_color: '#FF0000',
    top: 100,
    left: 120,
    team: 'A',
  },
  {
    id: 3,
    name: 'Yogesh',
    player_number: 8,
    jersey_color: '#FF0000',
    top: 380,
    left: 120,
    team: 'A',
  },
  {
    id: 4,
    name: 'Sandeep',
    player_number: 7,
    jersey_color: '#FF0000',
    top: 180,
    left: 300,
    team: 'A',
  },
  {
    id: 5,
    name: 'Ujjwol',
    player_number: 10,
    jersey_color: '#FF0000',
    top: 250,
    left: 260,
    team: 'A',
  },
];

export const teamB = [
  {
    id: 1,
    name: 'Sunil',
    player_number: 1,
    jersey_color: 'blue',
    top: 250,
    left: 630,
    team: 'B',
  },
  {
    id: 2,
    name: 'Sanjit',
    player_number: 4,
    jersey_color: 'blue',
    top: 180,
    left: 530,
    team: 'B',
  },
  {
    id: 3,
    name: 'Tapendra',
    player_number: 8,
    jersey_color: 'blue',
    top: 250,
    left: 380,
    team: 'B',
  },
  {
    id: 4,
    name: 'Bikash',
    player_number: 7,
    jersey_color: 'blue',
    top: 430,
    left: 450,
    team: 'B',
  },
  {
    id: 5,
    name: 'Inish',
    player_number: 10,
    jersey_color: 'blue',
    top: 100,
    left: 430,
    team: 'B',
  },
];
